### ISSUE TITLE
[Insight] Text files should end with a newline character - in app/config/config.yml, line 211

### ISSUE THREAD

**Issue by robwasripped** [robwasripped/eve#7]
**[in app/config/config.yml, line 211](https://github.com/robwasripped/eve/blob/5b83fe9ff739cee6888d5ea47bbd3c5697a05bab/app/config/config.yml#L211)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
        glyphicons-halflings-woff:
            inputs: '@AppBundle/Resources/vendor/node_modules/gentelella/vendors/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        glyphicons-halflings-woff2:
            inputs: '@AppBundle/Resources/vendor/node_modules/gentelella/vendors/bootstrap/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/43e5874d-c0f0-4047-ba54-2a3046f4c6fb/analyses/2)_
